add linux packaging
outscale/osc-cli pull request #81
Opened 2021-07-13 14:19 UTC by outscale-mgo

This add a pkg directory that contain a Makefile used to create an AppImage of osc-cli (here based on python 3.10.0).

note that: the makefile require appimagetool as dependency (findable here: https://github.com/AppImage/AppImageKit/tags) and is based on https://github.com/niess/python-appimage repository

I could download appimagetool in the Makefile too, if that suite you better ?

Also because I'm based on niess python-appimage repo, the Makefile need to stay updated, as niess seems to remove old python build.

Signed-off-by: Matthias Gatto <matthias.gatto@outscale.com>

2021-07-15 08:47 UTC, jerome-jutteau requested changes
Added some comments.
Also:

- Add a README.md in this new folder to explain
  - how to install builder dependencies (like [appimagetool](https://appimage-builder.readthedocs.io/en/latest/intro/install.html)
  - perform the build
  - install
- Edit /README.md to add few words about this way to package
- Could you move pkg/ content de pkg/linux as other OS should follow

2021-07-15 08:47 UTC, jerome-jutteau commented on pkg/Makefile
> +PY_VER=3.10
3.9 /  3.9.6 ?

2021-07-15 08:51 UTC, jerome-jutteau commented on pkg/Makefile
> +	cd osc-cli.AppDir/ && PIP_CONFIG_FILE=/dev/null usr/bin/pip$(PY_VER) install --isolated --root="" --ignore-installed --no-deps pylint
`for package in defusedxml fire xmltodict termcolor bandit pylint` ?

2021-07-15 09:36 UTC, outscale-mgo commented
>     * Could you move pkg/ content de pkg/linux as other OS should follow

My Idea was to one Makefile for all packages, so you would make, and the makefile would create Win + Linux + macos. and if you want only linux Package you can still use `make osc-cli-x86_64.AppImage`

2021-07-15 10:00 UTC, jerome-jutteau commented
> > ```
> > * Could you move pkg/ content de pkg/linux as other OS should follow
> > ```
> 
> My Idea was to one Makefile for all packages, so you would make, and the makefile would create Win + Linux + macos. and if you want only linux Package you can still use `make osc-cli-x86_64.AppImage`

Sure, we can have a top Makefile and OS-specific sub dirs to make clear which file belongs to which pkg system

2021-07-16 08:01 UTC, jerome-jutteau approved these changes

2021-07-16 08:01 UTC, merged